name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Debug job to see what branch info we have
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug branch info
      run: |
        echo "github.ref: ${{ github.ref }}"
        echo "github.ref_name: ${{ github.ref_name }}"
        echo "github.head_ref: ${{ github.head_ref }}"
        echo "Event name: ${{ github.event_name }}"

  # Code quality checks
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format clang-tidy cppcheck
        
    - name: Run clang-format check
      run: |
        if [ -f .clang-format ]; then
          find src test -name "*.hpp" -o -name "*.cpp" | xargs clang-format --dry-run --Werror --style=file
        else
          echo "No .clang-format file found, skipping format check"
        fi
        
    - name: Run static analysis  
      run: |
        echo "Current directory: $(pwd)"
        echo "Running cppcheck..."
        if command -v cppcheck &> /dev/null; then
          if [ -d "src" ]; then
            echo "Found src/ directory, running cppcheck on header files..."
            find src/ -name "*.hpp" -o -name "*.cpp" | xargs cppcheck --enable=warning,style,performance,portability --inline-suppr --quiet --error-exitcode=0
          else
            echo "src/ directory not found, skipping cppcheck..."
          fi
        else
          echo "cppcheck not found, skipping..."
        fi

  # Build and test on multiple platforms
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build-type: [Debug, Release]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Configure CMake
      run: |
        cd test
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} ..
        
    - name: Build
      run: |
        cd test/build
        cmake --build . --config ${{ matrix.build-type }}
        
    - name: Run tests
      run: |
        cd test/build
        ctest --output-on-failure --build-config ${{ matrix.build-type }}

  # Code coverage (Linux only)
  coverage:
    runs-on: ubuntu-latest
    # Temporarily removed condition for testing
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install coverage tools
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov
        
    - name: Build with coverage
      run: |
        cd test
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" ..
        cmake --build . --config Debug
        
    - name: Run tests with coverage
      run: |
        cd test/build
        ./bin/tests
        
    - name: Generate coverage report
      run: |
        cd test/build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --remove coverage.info '*/thirdparty/*' --output-file coverage.info
        lcov --list coverage.info
        
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: test/build/coverage.info
        fail_ci_if_error: true

  # Documentation generation
  documentation:
    runs-on: ubuntu-latest
    # Temporarily removed condition for testing
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
        
    - name: Generate documentation
      run: |
        cd docs/doxygen
        doxygen Doxyfile
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/doxygen/docs/html

  # Performance benchmarks
  benchmarks:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'develop') || contains(github.ref, 'fixing-cicd-pipeline') || github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Build benchmarks
      run: |
        cd test
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-O3 -DNDEBUG" ..
        cmake --build . --config Release
        
    - name: Run performance tests
      run: |
        cd test/build
        # Add performance benchmark execution here
        echo "Performance benchmarks would run here"
